<a href="https://colab.research.google.com/github/rb7488/Python-Library-/blob/main/DS_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

**NumPy**

In [ ]:
#revision
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print("Shape: ",b.shape) #shape tells the row and column available


[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)


In [ ]:
#indexing
print(b[0,0])
print(b[1,2])
print(b[:,1])
print(b[0])



1
6
[2 5]
[1 2 3]
[[1 2 3]
 [4 5 6]]
New Shape:  [[1 2 3]
 [4 5 6]]


In [ ]:
#basic operationn
arr=np.array([10,20,30,40])
print(arr+5)
print(arr*2)
print(arr/10)
print(np.sum(arr))
print(np.mean(arr))

[15 25 35 45]
[20 40 60 80]
[1. 2. 3. 4.]
100
25.0


In [ ]:
#reshape
x=np.array([1,2,3,4,5,6])
x_reshaped=x.reshape(2,3)
print(x_reshaped)
print("New Shape: ",x_reshaped)


[[1 2 3]
 [4 5 6]]
New Shape:  [[1 2 3]
 [4 5 6]]


In [ ]:
#slice
arr=np.array([10,20,30,40,50,60])

print(arr[1:4])
print(arr[:3])
print(arr[-3:])

[20 30 40]
[10 20 30]
[40 50 60]


In [ ]:
#practise question
ar=np.array([5,10,15,20,25,30])
print(ar)
print(ar*3)
print(ar+5)
new_ar=ar.reshape(2,3)
print(new_ar)
print("New array: ",new_ar)
print(new_ar[1])
print(new_ar[:2])


[ 5 10 15 20 25 30]
[15 30 45 60 75 90]
[10 15 20 25 30 35]
[[ 5 10 15]
 [20 25 30]]
New array:  [[ 5 10 15]
 [20 25 30]]
[20 25 30]
[[ 5 10 15]
 [20 25 30]]


In [1]:
import pandas as pd
df=pd.read_csv('data.csv')


FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

Data Visualization in Matplot